remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

title: Open Integration Hub
description: Open Source Integration Framework

url: "https://openintegrationhub.github.io/" 

aux_links:
  "Open Integration Hub on GitHub":
    - "//github.com/openintegrationhub"

footer_content: "Copyright &copy; 2019 <a href=\"https://cloudecosystem.org\">Cloud Ecosystem e.V.</a>"
